import './globals.css'
import Header from './component/Header'
import Footer from './component/Footer'

export const metadata = {
  title: 'Resume Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className="bg-cyan-600"><Header />{children}<Footer /></body>
    </html>
  )
}
